version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: avamj_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/avamj_db
      SECRET_KEY: "trocar_isso_em_producao"
      MOODLE_URL: "https://moodle.escola.com.br"
      MOODLE_TOKEN: "token_moodle_123"

volumes:
  mysql_data: